### ISSUE TITLE
User Search

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [MahdiMajidzadeh/salam#4]
we need user search in user list

**Comment by alizaya** [comment]
Done its work with like so you can only type part of mobile or name to search it

**Comment by MahdiMajidzadeh** [comment]
yes @alizaya

**Comment by MahdiMajidzadeh** [comment]
done in https://github.com/MahdiMajidzadeh/nahar/pull/3/commits/5504aa7d59fdfbe77c5fa7f1fd653040162bda8e
